### ISSUE TITLE
api.process(request). Internal server error

### ISSUE THREAD

**Issue by AndreiPaulau** [regulaforensics/DocumentReader-web-java-client#11]
Dear Support,
We’re trying to write a java client for the Document Reader Docker (regulaforensics/docreader:5.2.103350.2); however; am getting an internal server when calling the “api.process(request);”.
Also, I could see that the server logs is showing an exception on “flask/app.py” line 1950.
By the way, the default web page provided by the docker is working just fine.
Am using the same code found in the example on github: https://github.com/regulaforensics/DocumentReader-web-java-client/blob/master/example/src/main/java/com/regula/documentreader/webclient/example/Main.java (https://github.com/regulaforensics/DocumentReader-web-java-client/blob/master/example/src/main/java/com/regula/documentreader/webclient/example/Main.java)
[documentreader-serverlog.txt](https://github.com/regulaforensics/DocumentReader-web-java-client/files/5223093/documentreader-serverlog.txt)

**Comment by hleb-albau** [comment]
Баг заключается в следующем:
У фоток есть формат, когда кроме самой фотки в base64 еще в начало добавляется информация о типе фотки `'^data:image\/[a-z]+;base64`. Если не приложить фотку в определенный тип запроса, то на сервере во время обрезания префикса с типом фотки падается 500, так как мы пытаемся это сделать на null объекте.
На правильные запросы ни как не влияет, влияет только на bad requests

Фиксы:
- [ ] Добавить валидацию наличия фотки на клиента
- [ ] Добавить валидацию наличия фотки на сервере, чуть что кидать 400 ошибку(вместое 500)
- [ ] Добавить тест на текущий кейс

**Comment by hleb-albau** [comment]
fixed
