### ISSUE TITLE
how do you set the proxy ?

### ISSUE THREAD

**Issue by chehabz** [regulaforensics/DocumentReader-web-java-client#28]
how can you set the HTTP proxy?
need a username password and a server + port

**Comment by hleb-albau** [comment]
hello,

working on your question

**Comment by hleb-albau** [comment]
Assuming you have HTTP proxy, could, you, please, try this

```
        var proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("proxy_host", 8083));
        var proxyAuthenticator = new Authenticator() {
            @Override
            public Request authenticate(@Nullable Route route, Response response) throws IOException {
                String credential = Credentials.basic(username, password);
                return response.request().newBuilder()
                        .header("Proxy-Authorization", credential)
                        .build();
            }
        };
        
         var http_client = new OkHttpClient.Builder()
                .proxy(proxy)
                .proxyAuthenticator(proxyAuthenticator)
                .build();


        var api_client = new ApiClient(http_client);
        api_client.setBasePath("https://some_url_where_document_reader_started:8080/");
        var api = new DocumentReaderApi(api_client);
```        

In general, we use okhttp3 as HTTP client. You can find more options available in OkHttpClient.Builder() in okhttp3 docs.

Waiting your feedback :)

**Comment by mailspaghetti-admin** [comment]
So this wont work in java 8 and i need to know which version you are using so i can add it in the pom right?

**Comment by chehabz** [comment]
I suppose this wont work with java 8 without adding the okhttp3 to my pom file, do you have any specific version.

**Comment by hleb-albau** [comment]
our lib bundled with `com.squareup.okhttp3:okhttp:3.14.7` dependency in [maven metadata](https://maven.regulaforensics.com/RegulaDocumentReaderWebClient/com/regula/documentreader/webclient/5.5.3/webclient-5.5.3.pom). Thus, if you install our lib, maven/gradle should implicitly include okhttp3.

btw, [here](https://github.com/regulaforensics/DocumentReader-web-java-client/blob/master/client/build.gradle.kts) you can find actual versions of dependencies we use

**Comment by hleb-albau** [comment]
hello @chehabz,

Did you succeed with proxy integration?

**Comment by chehabz** [comment]
Unfortunately no as we’re planning to host the soln on azure on our
environment.

**Comment by hleb-albau** [comment]
close as stale
