### ISSUE TITLE
Mismatch of front and back page of document

### ISSUE THREAD

**Issue by kishoreaoe** [regulaforensics/DocumentReader-web-java-client#30]
Dear Team,

We are trying to pass two different images which belongs to different person (say front image id of person1, and then back image id of person2) for Regula "DocumentReaderApi".

After processing we are getting "CheckResult" as not ok. Is there any object/field can i refer that to get the appropriate issue. this would enhance our user experience alot.

artifact: webclient
version: 5.2.0

Thanks and Regards,
Kishore Kumar. K

**Comment by kishoreaoe** [comment]
Dear Team,
could you please help on this, as it is very much important for us in order to move ahead with regula framework..

**Comment by hleb-albau** [comment]
Dear kishoreaoe,

Sorry for the late reply. There is no single status field for that issue. But you can identify the issue by next logic:

``` response.status().getDetailsOptical().getText()``` is not ok.  
```
var fullNameField = response.text().getField(SURNAME_AND_GIVEN_NAMES);
fullNameField.valueList contains at least two entries with different pageIndex
fullNameField.status is not ok.  
```

All the best, Hleb

**Comment by kishoreaoe** [comment]
thanks alot. wil check on this , @hleb-albau .
one final query- is there any way to identify whether user uploaded the image has MRZ or not...  as per response we could a difference ( ContainerList -> detailsOptiocal -> mrz attribute...) can we use the same... value "1" means "MRZ is present" and "2" means "MRZ is not present"

**Comment by hleb-albau** [comment]
You are right. Two comments:
 - if you select a scenario, that not include mrz reading, that attribute will have a value of 2 (check was not performed).
 - if for any reason(for example, we can't recognize a document at all)  we do not read mrz value on a document, that attribute will have a value of 2 (check was not performed).

**Comment by kishoreaoe** [comment]
thanks alot.. understood the point..
